name: Check Branch Name

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "dev" || "$BRANCH_NAME" == "reports" ]]; then
            echo "Skipping branch name check for '$BRANCH_NAME'"
            exit 0
          fi

          if [[ ! $BRANCH_NAME =~ ^(bug|task|documentation|test)-[0-9]+-([a-z0-9-]+)$ ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not match the pattern 'task_name-number-sometext'"
            echo "Pattern must be one of: bug, task, documentation, test, followed by a number and a text separated by dashes."
            exit 1
          fi