name: Check Branch Name And File Structure

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "dev" || "$BRANCH_NAME" == "reports" ]]; then
            echo "Skipping branch name check for '$BRANCH_NAME'"
            exit 0
          fi

          if [[ ! $BRANCH_NAME =~ ^(bug|task|documentation|test)-[0-9]+-([a-z0-9-]+)$ ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not match the pattern 'task_type-number-description'"
            echo "Pattern must be one of: bug, task, documentation, test, followed by a number and a text separated by dashes."
            exit 1
          fi
          
      - name: Add label if check fails
        if: failure() 
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "invalid"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for disallowed directories or files
        run: |
          # Допустимые пути
          ALLOWED_PATHS=(
            "."
            "./train"
            "./Парадигмы программирования"
            "./Парадигмы программирования/Вариант 1/"
            "./Парадигмы программирования/Вариант 1/task"
            "./Парадигмы программирования/Вариант 1/test"
            "./Парадигмы программирования/Вариант 2"
            "./Парадигмы программирования/Вариант 2/task"
            "./Парадигмы программирования/Вариант 2/test"
            "./Введение в анализ данных"
            "./Введение в анализ данных/Вариант 1"
            "./Введение в анализ данных/Вариант 1/task"
            "./Введение в анализ данных/Вариант 1/test"
            "./Введение в анализ данных/Вариант 2"
            "./Введение в анализ данных/Вариант 2/task"
            "./Введение в анализ данных/Вариант 2/test"
            "./Введение в анализ данных/Вариант 3"
            "./Введение в анализ данных/Вариант 3/task"
            "./Введение в анализ данных/Вариант 3/test"
          )

          ALL_PATHS=$(find . -type d -not -path "./.git*" -not -path "./.github*")

          for path in $ALL_PATHS; do
            if [[ ! " ${ALLOWED_PATHS[@]} " =~ " $path " ]]; then
              echo "Error: Disallowed directory or file found: '$path'"
              exit 1
            fi
          done

          echo "All directories and files are valid."

      - name: Add label if check fails
        if: failure() 
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "invalid"

      - name: Remove label if check succeeds
        if: success()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "invalid"